### ISSUE TITLE
Display a small help about transfer direction switching

### ISSUE THREAD

**Issue by varasev** [poanetwork/bridge-ui#106]
It seems that some people don't understand that transfer is bidirectional: https://www.reddit.com/r/POA/comments/8ign8t/mainnet_bridge_app_seems_unidirectional/

I think some small text note should be displayed on the Bridge UI about how to change transfer direction.

**Comment by rstormsf** [comment]
Agree. we need to come up with some solution

**Comment by SiddigZeidan** [comment]
The message will be 
```
Please note the POA Bridge is the only live cross chain bridge that supports bi-directional transfers.  This means you can send tokens from the POA Network to the Ethereum network. You can ALSO send your tokens back from the Ethereum network to the POA Network.

Instructions are available to use the POA Bridge.
POA to Ethereum: https://youtube.com/watch?v=FtId3i0TWZQ
Ethereum to POA: https://youtube.com/watch?v=P1W1FHPhPT0
```
Pavel, designer, is trying to decide what the best way to display that info is. Weather in a popup window, or if it should be always displayed in the UI

**Comment by varasev** [comment]
I think it's better to always display it in the UI.

**Comment by acravenho** [comment]
@SiddigZeidan Shouldn't we be showing videos of POA bridge using Metamask as opposed to the videos above that show how to use the bridge without Metamask?

**Comment by akolotov** [comment]
Closing this issue due to migration to the [monorepo](https://github.com/poanetwork/tokenbridge). If it is still necessary to improve UI to notify the user about possibility to change the transfer direction, please open new issue in the monorepo.
