### ISSUE TITLE
New UI features

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/bridge-ui#112]
The following features and enhancements are open for discussion and we can decide as a team if:

1) They are feasible and doable
2) If they are a good enhancements
 
**Enhancement 1: Show user's wallet address on the Bridge UI**
User’s Ethereum wallet address somewhere displayed on the page. Give users comfort that they’ve successfully logged in on MetaMask extension AND synced to the website. Pavel has created a design where the user can see their address on top right

![image](https://user-images.githubusercontent.com/4807398/40035252-e4ad05b2-57ce-11e8-8aaf-9d7435d23f76.png)

![image](https://user-images.githubusercontent.com/4807398/40035262-edb62fd0-57ce-11e8-82d6-b98ad0c0ada5.png)

**Enhancement 2: Real-time view of how many tokens remaining in daily quota**
![image](https://user-images.githubusercontent.com/4807398/40035331-3515964a-57cf-11e8-91fb-c0c9617a2bf3.png)

**Enhancement 3:Real-time split between how many poa native tokens exists vs poa20 token. Animation showing recent transfers**

https://projects.invisionapp.com/share/NMIM5J0BC6H#/screens/296241748

**Comment by akolotov** [comment]
Addressed in #117
