### ISSUE TITLE
POA Bridge issues with Brave browser

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/bridge-ui#120]
The POA Bridge seems to work intermittently on the Brave browser. Different users reported issues about using it, with the screen freezing at the first step of block confirmation

![image](https://user-images.githubusercontent.com/4807398/40940027-782ee9d6-6814-11e8-8c1c-030294f04678.png)

![image](https://user-images.githubusercontent.com/4807398/40940068-96fb4698-6814-11e8-8094-687c46118032.png)

**Comment by patitonar** [comment]
I wasn't able to reproduce any issue on Brave browser. I tried sending several transactions and it worked correctly every time.

Tested on:
- Ubuntu 18.04.1 LTS
- Brave Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by rstormsf** [comment]
Brave browser probably fixed the issue as well

**Comment by pablofullana** [comment]
@SiddigZeidan any updates on this one? Shall we close it?

**Comment by SiddigZeidan** [comment]
Yup, Ill close
