### ISSUE TITLE
Display authority responsible for relay for CollectedSignatures on Events page

### ISSUE THREAD

**Issue by patitonar** [poanetwork/bridge-ui#123]
On Events page, it would be helpful to show  `authorityResponsibleForRelay` when displaying `CollectedSignatures` events

**Comment by akolotov** [comment]
It make sense to close this issue and address this functionality as part the issue ["Ability to call executeSignatures() by an end user from Bridge UI"](https://github.com/poanetwork/bridge-ui/issues/156)
