### ISSUE TITLE
Cannot deploy contracts using node deploy.js throws error

### ISSUE THREAD

**Issue by kpulkit29** [poanetwork/bridge-ui#127]
➜ node deploy.js
deploying storage for home validators
(node:2291) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at deployContract (/Users/pulkit29/Desktop/check/sokol-kovan-bridge/poa-bridge-contracts/deploy/src/deploymentUtils.js:41:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This error is thrown

**Comment by kpulkit29** [comment]
The .env file created is different from what is given in the README

**Comment by patitonar** [comment]
Hi @kpulkit29 , on the step of cloning poa-bridge-contracts, can you try cloning into `master` branch instead of the one suggested on README? 
```
git clone https://github.com/poanetwork/poa-bridge-contracts.git
```

**Comment by kpulkit29** [comment]
okay will try doing that

**Comment by kpulkit29** [comment]
node deploy.js
deploying storage for home validators
pending txHash 0x9b74b670968c0420dd1becee1a041ed0383b8e3afb8d43b7fb4f59c52a1a3609

cannot deploy on sokol chain
but home contract is being deployed on my sidechain

**Comment by kpulkit29** [comment]
DEPLOYMENT_ACCOUNT_ADDRESS=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
DEPLOYMENT_ACCOUNT_PRIVATE_KEY=""
DEPLOYMENT_GAS_LIMIT=4000002
DEPLOYMENT_GAS_PRICE=0
GET_RECEIPT_INTERVAL_IN_MILLISECONDS=3000

HOME_RPC_URL=https://sokol.poa.network
HOME_OWNER_MULTISIG=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_UPGRADEABLE_ADMIN_VALIDATORS=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_UPGRADEABLE_ADMIN_BRIDGE=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_DAILY_LIMIT=30000000000000000000000000
HOME_MAX_AMOUNT_PER_TX=1500000000000000000000000
HOME_MIN_AMOUNT_PER_TX=500000000000000000
HOME_REQUIRED_BLOCK_CONFIRMATIONS=1
HOME_GAS_PRICE=0

FOREIGN_RPC_URL=https://kovan.infura.io/mew
FOREIGN_OWNER_MULTISIG=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_UPGRADEABLE_ADMIN_VALIDATORS=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_UPGRADEABLE_ADMIN_BRIDGE=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_DAILY_LIMIT=1000000000000000000
FOREIGN_MAX_AMOUNT_PER_TX=100000000000000000
FOREIGN_MIN_AMOUNT_PER_TX=10000000000000000
FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS=8
FOREIGN_GAS_PRICE=10

REQUIRED_NUMBER_OF_VALIDATORS=1
VALIDATORS="0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D"

Using this .env file for still not able to deploy

**Comment by kpulkit29** [comment]
if I deploy the foreign bridge then it works fine but home bridge creates problem

**Comment by patitonar** [comment]
Can you try changing the following .env variables:
`DEPLOYMENT_GAS_PRICE=10`
`HOME_GAS_PRICE=1`

**Comment by kpulkit29** [comment]
Thank You sir it is working fine now.Instead of sokol network can I use my
sidechain?

Thanks,
Pulkit

**Comment by kpulkit29** [comment]
Sir the changes you mentioned in .env file make the home bridge work but
now the foreign bridge fails.
Thanks,
Pulkit

**Comment by kpulkit29** [comment]
everything worked when I added ether to address that holds ether in both
kovan and sokol

Thanks for the support.I am currently working with a blockchain based
startup named SpringRole we want to get our contracts on PoA network.So is
it possible that me and my CEO can have a call with for some discussion on
how can we leverage your product

**Comment by kpulkit29** [comment]
It is not specified in the README what should be the format of password.txt file.I am using two different accounts so does that mean I need to make two different password files.

The error I get is
WARN:ethstore::accounts_dir::disk: Invalid key file: "keys/password1.txt" (Error("expected ident", line: 1, column: 2))
WARN:ethstore::accounts_dir::disk: Invalid key file: "keys/password2.txt" (Error("expected ident", line: 1, column: 2))
WARN:bridge: Can't establish an RPC connection: Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State {next_error: None, backtrace: None })

**Comment by kpulkit29** [comment]
is it compulsory to have different validators for home and foreign bridge

**Comment by akolotov** [comment]
> is it compulsory to have different validators for home and foreign bridge

No. It is assumed that one particular validator will use the same private key to sign transactions on home and foreign side of the bridge. That's why we don't provide ability to configure different validator addresses in the bridge contracts (`VALIDATORS` parameter in `.env` file)

**Comment by akolotov** [comment]
> It is not specified in the README what should be the format of password.txt file.

Please create a separate issue for this.
