### ISSUE TITLE
Account invalid error when using single validator

### ISSUE THREAD

**Issue by kpulkit29** [poanetwork/bridge-ui#131]
env RUST_LOG=info ./poa-bridge/target/release/bridge --config config.toml --database db.toml
INFO:bridge: Parsing cli arguments
INFO:bridge: Loading config
INFO:bridge: Starting event loop
INFO:bridge: Home rpc host https://sokol.poa.network
INFO:bridge: Foreign rpc host https://kovan.infura.io/mew
INFO:bridge: Establishing connection:
INFO:bridge:   using RPC connection
WARN:bridge: Can't establish an RPC connection: Error(AccountError(InvalidAccount), State { next_error: None, backtrace: None })
account error InvalidAccount

I am using a single validator config.toml and password.txt are in same folder

**Comment by akolotov** [comment]
Please open the issue with the same description in `https://github.com/poanetwork/poa-bridge` repo. Thanks.

**Comment by kpulkit29** [comment]
Sir please have a look at it.I have put a new issue on poa-bridge repo
