### ISSUE TITLE
UI update required

### ISSUE THREAD

**Issue by Martin1209** [poanetwork/bridge-ui#133]
![image](https://user-images.githubusercontent.com/38187513/44165961-09019b80-a0c2-11e8-9a30-ae77efa72077.png)

What's metamask... ;)

**Comment by rstormsf** [comment]
[metamask](https://metamask.io )
@Martin1209

**Comment by acravenho** [comment]
@rstormsf I think they're referring to updating to Nifty Wallet

**Comment by akolotov** [comment]
Hmm. But MetaMask will also work, right? Does it make sense to use a common name like "an extension providing Web3 interface" and links it to a page which provide the list of supported extensions?

**Comment by acravenho** [comment]
I think it might be a better user experience to list them both directly in the popup. 

"You need to install [Nifty Wallet](https://chrome.google.com/webstore/detail/nifty-wallet/jbdaocneiiinmjbjlgalhcelgbejmnid) or [Metamask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn) and select an account."

**Comment by jflowers1974b** [comment]
BUMP - Since I removed MetaMask (don't like the new full page interface) and using Nifty... Love to make sure that the site works with Nifty only folks.

**Comment by akolotov** [comment]
Addressed in #138
