### ISSUE TITLE
Update Bridge UI to reflect installation with node-js bridge

### ISSUE THREAD

**Issue by jlogelin** [poanetwork/bridge-ui#140]
Currently the instructions for setting up the bridge UI does not work with an ERC20 <-> ERC20 node-js bridge deployment.

Current configuration requires an additional step to configure git submodules

1. Copy 'poa-bridge-contracts/build/contracts' folder to 'bridgeui-src'
2. Move to 'develop' branch and initialize the submodules.
```
git checkout develop
git submodule init
git submodule update
```

**Comment by akolotov** [comment]
Addressed in #143
