### ISSUE TITLE
Update metamask popup

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/bridge-ui#151]
Old view 

<img width="1298" alt="image 2018-11-27 at 2 43 14 pm" src="https://user-images.githubusercontent.com/16716926/49104547-e8cba600-f286-11e8-97ab-3b590519e281.png">

New view

![poa_bridge_popup_nw_mm](https://user-images.githubusercontent.com/16716926/49104433-a3a77400-f286-11e8-8be3-4c5d08adb281.png)

Zeplin: https://zpl.io/a8P3Bjx

**Comment by igorbarinov** [comment]
@akolotov please assign the issue

**Comment by akolotov** [comment]
@fernandomg could you take a look?

**Comment by akolotov** [comment]
Open questions and recommendation can be found in https://github.com/poanetwork/bridge-ui/issues/147

**Comment by fernandomg** [comment]
Just want to clarify and maybe have a better UX.

Currently the modal with the 'Error' is being displayed despite if the wallet is not installed or locked. The message is quite generic and may lead to confusion.

I can identify each type of error and display:
 - the 'Metamask/Nifty' wallet modal when there's no wallet installed,
 - and the 'Error' modal with a message asking the user to unlock his/her wallet.

Both errors are triggered already, but just need to be properly handled.

---
**Screenshots (check the console error message displayed at the bottom)**

### Unlock
![image](https://user-images.githubusercontent.com/3315606/49155792-975cfe80-f2fa-11e8-8250-4c6b22e685d5.png)
### Install
![image](https://user-images.githubusercontent.com/3315606/49155804-9deb7600-f2fa-11e8-9a9a-0e10ff66fe5b.png)

Any thoughts @akolotov @igorbarinov?

**Comment by akolotov** [comment]
My bid is that we need to handle these two cases in different way.
