### ISSUE TITLE
Metamask detection problem

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#161]
![image](https://user-images.githubusercontent.com/9360827/50137990-d4dff680-02be-11e9-88a0-557b163c5eb5.png)
![2018-12-18 12 17 36](https://user-images.githubusercontent.com/9360827/50138033-f4771f00-02be-11e9-8bb2-c142cd5bd8e4.jpg)

Metamask 5.2.2

**Comment by rstormsf** [comment]
![image](https://user-images.githubusercontent.com/9360827/50140441-8c2c3b80-02c6-11e9-8f00-b3c9aea983d2.png)

Production version doesn't align with master branch.
I don't see same source code such as `ethereum.enable()`
EIP1102
https://github.com/poanetwork/bridge-ui/blob/master/src/stores/utils/web3.js#L15

**Comment by akolotov** [comment]
@rstormsf thanks!
Right, the changes made for https://github.com/poanetwork/bridge-ui/issues/139 were not backported to the old version to the Bridge UI.

**Comment by akolotov** [comment]
The suggestion is to do the following:
1. Create two branches: `master-1.x` and `develop-1.x` based on https://github.com/poanetwork/bridge-ui/commit/9651de42bb96502d0a5498b0ac5b2dec12762521. The branch `develop-1.x` will be used for collecting and soaking backports and security updates. The branch `master-1.x` will be used for changes that need to go to `https://bridge.poa.net` (netlify auto deploy will be linked with this branch).
2. Prepare a backport for #139 into `develop-1.x`. Link the branch `develop-1.x` with demo POA bridge in the Sokol network.
3. As soon as everything is tested in `develop-1.x` merge the changes to `master-1.x` and produce the new release.

**Comment by rstormsf** [comment]
@igorbarinov the bug is valid. the bridge was not working.

**Comment by akolotov** [comment]
Addressed in #162
