### ISSUE TITLE
poaexplorer with old http protocol url

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#164]
Steps: Use trust wallet to transfer from POA20 to POA

The URL tried to navigate to poaexplorer and didn't succeed

![image 2018-12-19 22 38 53](https://user-images.githubusercontent.com/9360827/50237482-dd2f5300-03de-11e9-87ab-b007c04c2c9e.jpg)

**Comment by akolotov** [comment]
The issue was split. There are two issues now:
* [poaexplorer with old http protocol url](#164)
* [Error that transaction was rejected appeared in TrustWallet](#171)

**Comment by akolotov** [comment]
This issue is to replace links to poaexplorer.com and sokol-explorer.poa.network to corresponding links to the BlockScout.

**Comment by akolotov** [comment]
Addressed in #174
