### ISSUE TITLE
update to lastest bridge versions

### ISSUE THREAD

**Issue by branciard** [poanetwork/bridge-ui#181]
Hi,
I try to update to latest bridges version : 
[poa-bridge-contracts 2.2.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.2.0)
[token-bridge 1.1.0]( https://github.com/poanetwork/token-bridge/releases/tag/1.1.0)
[bridge-ui 2.0.0](https://github.com/poanetwork/bridge-ui/releases/tag/2.0.0)

Are thoses versions compatible ? 

In `ERC-ERC mode`, with a transfer from `Foreign` to `Home`, it is stuck at "Validators Verifying Transaction..." in bridge-UI.

token bridges logs seems correct with 1 tx in `bridge_affirmation` and 1 tx in `bridge_senderhome` :  

```
ubuntu@ip-:~/token-bridge$ docker-compose logs -f
Attaching to token-bridge_bridge_affirmation_1, token-bridge_bridge_senderforeign_1, token-bridge_bridge_request_1, token-bridge_bridge_collected_1, token-bridge_bridge_senderhome_1, token-bridge_redis_1, token-bridge_rabbit_1
bridge_senderforeign_1  |
bridge_senderforeign_1  | > bridge-nodejs@1.0.0 sender:foreign /bridge
bridge_senderforeign_1  | > ./scripts/start-worker.sh sender foreign-sender "true"
bridge_senderforeign_1  |
bridge_affirmation_1    |
bridge_affirmation_1    | > bridge-nodejs@1.0.0 watcher:affirmation-request /bridge
bridge_affirmation_1    | > ./scripts/start-worker.sh watcher affirmation-request-watcher "true"
bridge_affirmation_1    |
bridge_affirmation_1    | {"level":50,"time":1548685932867,"msg":"Transactions to send: 1","validator":"0xabcd1339Ec7e762e639f4887E2bFe5EE8023E23E","name":"watcher-erc-erc-affirmation-request","v":1}
bridge_collected_1      |
bridge_collected_1      | > bridge-nodejs@1.0.0 watcher:collected-signatures /bridge
bridge_collected_1      | > ./scripts/start-worker.sh watcher collected-signatures-watcher "true"
bridge_collected_1      |
bridge_senderhome_1     |
bridge_senderhome_1     | > bridge-nodejs@1.0.0 sender:home /bridge
bridge_senderhome_1     | > ./scripts/start-worker.sh sender home-sender "true"
bridge_senderhome_1     |
bridge_senderhome_1     | {"level":50,"time":1548685933053,"msg":"Sending transaction with nonce 39","validator":"0xabcd1339Ec7e762e639f4887E2bFe5EE8023E23E","name":"sender-home","v":1}
bridge_request_1        |
bridge_request_1        | > bridge-nodejs@1.0.0 watcher:signature-request /bridge
bridge_request_1        | > ./scripts/start-worker.sh watcher signature-request-watcher "true"
bridge_request_1        |
```

I use the new secure docker-compose in token-bridge. Maybe there is a link.
First, I adjust startup for rabbit connection to be ready before others containers start ( to remove connections errors in logs)  : 

```
docker-compose up -d rabbit  
docker-compose up -d redis
# wait rabbit connection to be ready
sleep 30
docker-compose up -d --build
```

But now logs seems correct but it is stuck on "Validators Verifying Transaction...." 

I will add here if I found more relevant logs or clues.

**Comment by branciard** [comment]
Here my token bridge .env file
```
BRIDGE_MODE=ERC_TO_ERC
HOME_POLLING_INTERVAL=5000
FOREIGN_POLLING_INTERVAL=1000
ALLOW_HTTP=yes
HOME_RPC_URL=http://--valid--ip--here:8545
FOREIGN_RPC_URL=http://-valid--ip--here:9545
HOME_BRIDGE_ADDRESS=0x37B5914B0F1b17C847F1239383489dBe078F6019
FOREIGN_BRIDGE_ADDRESS=0x37B5914B0F1b17C847F1239383489dBe078F6019
ERC20_TOKEN_ADDRESS=0x9Abfcd68c61E6C6C673c981e5DB658283Bf19dbD

VALIDATOR_ADDRESS=0xabcd1339Ec7e762e639f4887E2bFe5EE8023E23E
VALIDATOR_ADDRESS_PRIVATE_KEY=--valid--private--key--here

HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
HOME_GAS_PRICE_SPEED_TYPE=standard
HOME_GAS_PRICE_FALLBACK=1000000000
HOME_GAS_PRICE_UPDATE_INTERVAL=600000

FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
FOREIGN_GAS_PRICE_SPEED_TYPE=standard
FOREIGN_GAS_PRICE_FALLBACK=1000000000
FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000


#QUEUE_URL=amqp://127.0.0.1
#QUEUE_URL=amqp://rabbit
QUEUE_URL=amqp://rabbit:5672
#QUEUE_URL=amqp://rabbit:5673?

#REDIS_URL=redis://127.0.0.1:6379
REDIS_URL=redis://redis:6379

REDIS_LOCK_TTL=1000

HOME_START_BLOCK=217
FOREIGN_START_BLOCK=235

LOG_LEVEL=error
MAX_PROCESSING_TIME=20000

#testing accs
USER_ADDRESS=0xabcd1339Ec7e762e639f4887E2bFe5EE8023E23E
USER_ADDRESS_PRIVATE_KEY=--valid--private--key--here
HOME_MIN_AMOUNT_PER_TX=0.001
FOREIGN_MIN_AMOUNT_PER_TX=0.001
HOME_TEST_TX_GAS_PRICE=1000000000
FOREIGN_TEST_TX_GAS_PRICE=1000000000
```

Reading the env.example history I see that VALIDATOR_ADDRESS has been removed here : 
https://github.com/poanetwork/token-bridge/commit/8fcb8baa5413058aa957a205e178b83e68b70f17#diff-cbfd64a28982a1818f2b5f16e7f9d634
but still present in docker-compose :  https://github.com/poanetwork/token-bridge/blob/master/docker-compose.yml#L53 . Maybe there is something wrong with the VALIDATOR_ADDRESS usage.

**Comment by akolotov** [comment]
Right. it could be. I need more time to investigate. We changed a procedure to run containers in order to hide the validator's private key if its address is only needed. So, probably we didn't reflect this in the documentation.

**Comment by branciard** [comment]
In fact, I observe random behaviour, sometimes it passes, sometimes it stays stuck at "Validators Verifying Transaction....". I have to narrow down the problem on my side before investigation.

**Comment by branciard** [comment]
The random mystery is solved :). It works until I use my `MAX_AMOUNT_PER_TX` limit... 

My case is that I use external `erc20` so the UI control [here](https://github.com/poanetwork/bridge-ui/blob/develop/src/components/Bridge.js#L125) for max per tx is bypassed. 

But after when validator executeAffirmation the [contract control here](https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/BasicHomeBridge.sol#L19) trigger [AmountLimitExceeded event here](https://github.com/poanetwork/poa-bridge-contracts/blob/master/contracts/upgradeable_contracts/erc20_to_erc20/HomeBridgeErcToErc.sol#L82) as expected. 

This `AmountLimitExceeded event` is never treated in the [getEvents function](https://github.com/poanetwork/bridge-ui/blob/master/src/stores/HomeStore.js#L182). Only AffirmationCompleted event will change the status and set new step. And so It stay 'stuck' on the interface at "Validators Verifying Transaction...." .

I close this issue because the mystery is solved. 

Do you think I need to create 2 new issues for robustess UI improvement ?: 

1 - keep UI limit controls for external ERC20 too [here](https://github.com/poanetwork/bridge-ui/blob/develop/src/components/Bridge.js#L125) ,  because it will failed later with the smart contract `AmountLimitExceeded event` triggered.

and/or

2 - treat potential `AmountLimitExceeded event` in the [`getEvents` function](https://github.com/poanetwork/bridge-ui/blob/master/src/stores/HomeStore.js#L182). Something like this : 

```
const amountLimitExceededEvents = homeEvents.filter(
        (event) => {
         return event.event === "AmountLimitExceeded" 
})
amountLimitExceededEvents.forEach(event => {
          this.alertStore.setLoading(false)
          this.alertStore.pushError(`cannot be proceed : amountLimitExceeded `+ blabla values here )
          ...
            remove event from list ?.
          ...
})
```
