### ISSUE TITLE
Add AlphaWallet as a supported wallet for xdai bridging 

### ISSUE THREAD

**Issue by James-Sangalli** [poanetwork/bridge-ui#185]
![unnamed](https://user-images.githubusercontent.com/16630514/52950442-49c0d100-33d3-11e9-97e6-694571803201.png)

Android app: https://github.com/AlphaWallet/alpha-wallet-android

iOS app: https://github.com/AlphaWallet/alpha-wallet-ios

**Comment by akolotov** [comment]
Hi @James-Sangalli! 
If you create a PR for the `develop` branch with such functionality it is OK for us to include it in our code base.
