### ISSUE TITLE
Update style for ethereum classic network 

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/bridge-ui#190]
Zeplin

Main - https://zpl.io/aXP8Qvj
Details popup - https://zpl.io/VkGvk68
Info allert - https://zpl.io/VYK8jgd
Error allert - https://zpl.io/bzNeJg8
Statistics - https://zpl.io/bzNeJg7
Status - https://zpl.io/2EBoDNn

**Comment by SurfingNerd** [comment]
can you invite me on zpl.io ? it tells "You’re not invited to this project".
Is it about of CI and theming:
i have refactored the bridge with the ability to define a  color theme.. 
https://github.com/lab10-coop/artis-bridge-ui/blob/ARTIS-sigma/src/assets/stylesheets/themes/colors_poa.scss
