### ISSUE TITLE
ETH Classic styles' changes

### ISSUE THREAD

**Issue by gabitoesmiapodo** [poanetwork/bridge-ui#194]
Updated design: https://zpl.io/2Gy5d09

1. Change logo for all pages to

![image](https://user-images.githubusercontent.com/4015436/54991639-240f8480-4f9c-11e9-96c7-a362a5fe8ae6.png)

2. 2 rows for networks

![image (1)](https://user-images.githubusercontent.com/4015436/54991668-34276400-4f9c-11e9-8acd-8105d94542e7.png)

![Pasted_image_at_2019-03-25__11_38_PM](https://user-images.githubusercontent.com/4015436/54991685-3ab5db80-4f9c-11e9-991f-dd362d07f4a0.png)

3. Change old green color to new (only when background is white)

![image (2)](https://user-images.githubusercontent.com/4015436/54991725-4dc8ab80-4f9c-11e9-8738-b5430cf2adb9.png)

![Pasted_image_at_2019-03-25__11_39_PM](https://user-images.githubusercontent.com/4015436/54991729-50c39c00-4f9c-11e9-9d10-01aa3eefaf32.png)

for all pages `#2be187`

4. Change logo for ETH

![image (3)](https://user-images.githubusercontent.com/4015436/54991767-66d15c80-4f9c-11e9-9732-6e8ae40354dd.png)

5. Remove “2018 POA. All right reserved.”

![image (4)](https://user-images.githubusercontent.com/4015436/54991799-7355b500-4f9c-11e9-9b12-f08a67a7f8bf.png)

**Comment by akolotov** [comment]
Are you sure that we should remove "2018 POA. All rights reserved." at all? Ziggy opened yesterday the PR where he changed the year label: https://github.com/poanetwork/bridge-ui/pull/193

**Comment by gabitoesmiapodo** [comment]
It was requested by @igorbarinov 

Not sure if it's only for this theme (ETH Classic) or all themes though.

**Comment by akolotov** [comment]
Thanks! Confirmed with @igorbarinov. We don't need this line at all. I will add a comment to Ziggy's PR.
