### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#20]
- [ ] Make it more modular by decoupling React components into tiny modules

- [ ] send sweetalert when the token is received on another chain

**Comment by patitonar** [comment]
@rstormsf After reviewing the code, here are some improvements I can start working on to make the components more reusable and taking test into consideration:

- Clean code: Fix warnings, unused variables
- mobx Stores: Decouple store logic from web3 or order services into separate functions
- Refactor events components into reusable components
- Refactor Bridge component decoupling logic from presentational functions

**Comment by rstormsf** [comment]
sounds good to me

**Comment by pablofullana** [comment]
@patitonar @rstormsf shall we close this issue now that all of the related PRs have been merged?

**Comment by patitonar** [comment]
@rstormsf we can close this issue now that all PRs have been merged
