### ISSUE TITLE
If transfer triggered from wrong network, loading still apprears

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#42]
https://cl.ly/16131h2p2k05

**Comment by dennis00010011b** [comment]
The same picture if user clicks the  button 'transfer' with the empty 'amount' field

**Comment by patitonar** [comment]
@rstormsf @dennis00010011b can we close this issue? I think is was already solved on #59

**Comment by akolotov** [comment]
It was addressed by #59. If you have any objections please re-open the issue.
