### ISSUE TITLE
After open the  bridge web page  the transfer direction doesn't match the  selected network in Metamask

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/bridge-ui#58]
#### Steps to reproduce:
1. Open browser, activate Metamask, select Kovan network
2. Open https://bridge.poa.net/
3. Observe arrow direction, try to transfer tokens

#### Expected result: 
  - after open the  bridge web page  the transfer direction should be according with selected network in Metamask

#### Actual result:
 - direction by default from Home to Foreign account
 - disable to transfer tokens from Foreign to Home
 - error message: "Please switch metamask network to Sokol"

<img width="1440" alt="screen shot 2018-05-02 at 10 30 27" src="https://user-images.githubusercontent.com/14067096/39539362-3e1973e0-4df4-11e8-9e70-a466fe45fc13.png">

**Comment by patitonar** [comment]
@rstormsf @dennis00010011b can we close this issue? It was fixed on #59

**Comment by akolotov** [comment]
It was fixed on #59. If you have any objections please re-open the issue.
