### ISSUE TITLE
Wait for 8 block confirmations on Foreign

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#68]

**Comment by igorbarinov** [comment]
https://commerce.coinbase.com/faq

How many confirmations are required for each cryptocurrency?

The number of confirmations required depends on the cryptocurrency used to pay. We will be making this a setting in the future but for now the table below documents the number of confirmations required per currency:

Cryptocurrency | Confirmations
-- | --
Bitcoin | 1
Bitcoin Cash | 1
Ethereum | 8
Litecoin | 2
