### ISSUE TITLE
it should not look like clickable link

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-ui#82]
![image](https://user-images.githubusercontent.com/9360827/39783180-3653b0ba-52e2-11e8-9705-0543cd18eb06.png)

also the style looks weird, feels like `justify-content` was used.

the Checkmark looks too close to the text.

**Comment by StarGonchar** [comment]
![report](https://user-images.githubusercontent.com/24562707/39817124-f0442054-53a5-11e8-9e98-4a052fccf76c.jpg)
report

**Comment by patitonar** [comment]
@rstormsf I think this issue was fixed as part of #89

**Comment by igorbarinov** [comment]
Fixed by Ziggy with suggestions from lawyers about disclaimer in #89
